apiVersion: snorlax.moon-society.io/v1beta1
kind: SleepSchedule
metadata:
  namespace: default
  name: nginx
spec:
  wakeTime: '8am'
  sleepTime: '2pm'
  timezone: 'America/New_York'
  deploymentName: nginx-deployment
  replicaCount: 2
  ingressName: nginx-ingress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /path-one
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /path-two
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
