apiVersion: snorlax.moon-society.io/v1beta1
kind: SleepSchedule
metadata:
  namespace: default
  name: dummy
spec:
  wakeTime: '8am'
  sleepTime: '2pm'
  timezone: 'America/New_York'
  deploymentName: dummy-deployment
  ingressName: dummy-ingress
  wakeReplicas: 2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          # image: nginx:latest
          image: okteto/example-react
          ports:
            # - containerPort: 80
            - containerPort: 9000
#
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
          - path: /path-one
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
          - path: /path-two
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  selector:
    app: dummy
  ports:
    - protocol: TCP
      port: 80
      # targetPort: 80
      targetPort: 9000
