name: Build Docker image

on:
  push:
    branches: [ main ]

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build proxy image
      run: make proxy-build

    - name: Build operator image
      run: make operator-build